version: '3.9'
services:
  deepin-backend-admin:
    networks:
      - prisma-network
    build:
      context: .
      dockerfile: apps/deepin-backend-admin/Dockerfile
      target: build
    command: npm run serve:deepin-backend-admin
    ports:
      - "3000:3000"
    depends_on:
      postgres_db:
        condition: service_healthy
    environment:
      DATABASE_URL: "postgresql://postgres:prisma@postgres_db:5432/postgres?schema=public"
      JWT_ACCESS_SECRET: "dsaa"
      JWT_REFRESH_SECRET: "asdasd"

  deepin-backend-microservices:
    networks:
      - prisma-network
    build:
      context: .
      dockerfile: apps/deepin-backend-microservices/Dockerfile
      target: build
    command: npm run serve:deepin-backend-microservices
    ports:
      - "4200:4200"
    depends_on:
      postgres_db:
        condition: service_healthy
    environment:
      DATABASE_URL: "postgresql://postgres:prisma@postgres_db:5432/postgres?schema=public"
      JWT_ACCESS_SECRET: ""
      JWT_REFRESH_SECRET: ""
      AMQP_EXCHANGE: socket
      AMQP_USER: guest
      AMQP_PASSWORD: guest
      AMQP_HOSTNAME: localhost
      AMQP_QUEUE: socket

  postgres_db:
    image: postgres:15
    hostname: postgres_db
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: prisma
    ports:
      - '5432:5432'
    networks:
      - prisma-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      interval: 5s
      timeout: 2s
      retries: 20

networks:
  prisma-network:
    name: prisma-network
